# Generated by Django 5.2.15 on 2026-06-16 20:08

from typing import ClassVar

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: ClassVar[list] = []

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="BibliographicWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "normalized_title",
                    models.CharField(db_index=True, editable=False, max_length=255),
                ),
                ("description", models.TextField(blank=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "normalized_name",
                    models.CharField(editable=False, max_length=255, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="BookEdition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("publisher", models.CharField(blank=True, max_length=255)),
                ("publication_year", models.PositiveIntegerField(blank=True, null=True)),
                ("language", models.CharField(default="en", max_length=16)),
                (
                    "isbn",
                    models.CharField(blank=True, max_length=13, null=True, unique=True),
                ),
                ("description", models.TextField(blank=True)),
                ("external_identifiers", models.JSONField(blank=True, default=dict)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="editions",
                        to="catalog.bibliographicwork",
                    ),
                ),
            ],
            options={
                "ordering": ("work__title", "publication_year", "id"),
            },
        ),
        migrations.CreateModel(
            name="ExternalSourceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_name", models.CharField(max_length=64)),
                ("source_identifier", models.CharField(max_length=255)),
                ("source_url", models.URLField(blank=True)),
                ("license_note", models.CharField(blank=True, max_length=255)),
                ("imported_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("fetched_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "edition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_records",
                        to="catalog.bookedition",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_records",
                        to="catalog.bibliographicwork",
                    ),
                ),
            ],
            options={
                "ordering": ("source_name", "source_identifier"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_name", "source_identifier"),
                        name="unique_source_identifier",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkContributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("author", "Author"),
                            ("editor", "Editor"),
                            ("translator", "Translator"),
                            ("illustrator", "Illustrator"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "contributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_contributors",
                        to="catalog.contributor",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_contributors",
                        to="catalog.bibliographicwork",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("work", "contributor", "role"),
                        name="unique_work_contributor_role",
                    ),
                ],
            },
        ),
    ]
