# Generated by Codex for edition cover support.

from typing import ClassVar

from django.db import migrations, models

from libraryops.catalog.models import (
    edition_cover_upload_to,
    validate_cover_image_format,
    validate_cover_image_size,
)


class Migration(migrations.Migration):
    """Add edition cover URL and uploaded image support."""

    dependencies: ClassVar[list] = [
        ("catalog", "0001_initial"),
    ]

    operations: ClassVar[list] = [
        migrations.AddField(
            model_name="bookedition",
            name="cover_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="bookedition",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=edition_cover_upload_to,
                validators=[
                    validate_cover_image_size,
                    validate_cover_image_format,
                ],
            ),
        ),
    ]
