# Generated by Django 5.2.15 on 2026-06-16 20:08

from typing import ClassVar

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import libraryops.circulation.models


class Migration(migrations.Migration):
    initial = True

    dependencies: ClassVar[list] = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checked_out_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "due_at",
                    models.DateTimeField(default=libraryops.circulation.models.default_due_at),
                ),
                ("returned_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "copy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loans",
                        to="inventory.bookcopy",
                    ),
                ),
            ],
            options={
                "ordering": ("-checked_out_at",),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("returned_at__isnull", True)),
                        fields=("copy",),
                        name="unique_active_loan_per_copy",
                    ),
                ],
            },
        ),
    ]
