# Generated by Django 5.2.15 on 2026-06-16 20:08

from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: ClassVar[list] = [
        ("catalog", "0001_initial"),
    ]

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="BookCopy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barcode", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("on_loan", "On loan"),
                            ("maintenance", "Maintenance"),
                            ("lost", "Lost"),
                            ("archived", "Archived"),
                        ],
                        default="available",
                        max_length=32,
                    ),
                ),
                ("shelf_location", models.CharField(blank=True, max_length=64)),
                ("condition_note", models.TextField(blank=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="copies",
                        to="catalog.bookedition",
                    ),
                ),
            ],
            options={
                "ordering": ("barcode",),
            },
        ),
    ]
